version: "3.4"
services:
  client:
    container_name: ivy-client-sample
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  server:
    container_name: ivy-server-sample
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
